"""Convert the pickles generated by parallel_rollout_main.py to tf records."""
import pickle

from absl import app
from absl import flags

from rl755.common import structs


def main(_):
  pass


if __name__ == '__main__':
  app.run(main)
